---
title: "HW week 6"
Author: Audrey Tjahjadi
output: html_document
---

```{r}
z.prop.test<-function(p1, p2 = NULL, n1, n2 = NULL, p0, alternative = "two.tailed", conf.level = 0.95, alpha = 0.05, k = 10){
  #this is the basic function template
  p<- rep(NA, k) 
  #p0 stands for population proportion, p1 is pop1, p2 is pop2
  for (i in 1:k) {
    s<- sqrt((p0 * (1-p0))/n1)
    z<- ((p1-p2)-0)/(sqrt((p0*(1-p0)*((1/n1)+(1/n2)))))
    z2<- ((p1-p0)/s)
    
  if (alternative == "less") {
      p[i]<- pnorm(z, lower.tail = TRUE)
      
      if(is.null(p2)) { 
        #condition for if p2 is null
      p[i] <- pnorm(z2) 
      }
  }
  
  if(alternative == "greater") {
      p[i] <- pnorm (z, lower.tail = FALSE)
      #or use p[i] <- pt(t, df = n-1, lower.tail = TRUE)
      
      if(is.null(p2)) {
        p[i] <- pnorm(z2) 
      }
  }
  
  if(alternative == "two.tailed") {
      if (z > 0)
       {
        p[i] <- 2 * pnorm(z, lower.tail = FALSE)
       }
      if (z < 0)
       {
        p[i] <- 2 * pnorm(z, lower.tail = TRUE)
      } 
    
      if(is.null(p2)) {
        p[i] <- pnorm(z2) 
       }
      if(is.null(n2)) {
        p[i] <- pnorm(z2)
      }
  }
  if(n1*p1 < 5) {
      warning("conditions not met")
    #wasn't sure which n or p to use so i chose n1 and p1
    #under this condition normality cannot be assumed
  }
    
  if(n1 * (1-p1) < 5) {
      warning("conditions not met")
    #under this condition normality cannot be assumed
  }
  ci<-(p2-p1) + c(-1,1) * qnorm(0.975) * sqrt((p1*(1-p1)/n1)+(p2*(1-p2)/n2))
  }
  
  return(list(z, p[i], ci)) 
  #i think this is right but I was very confused on how to get the confidence interval here 
}
```

```{r}
ztest1<-z.prop.test(.3, .5, 30, 35, .4, alternative = "less", conf.level = 0.95, alpha = 0.05, k = 10)
ztest1

```

```{r}
d<- "C:/Users/Audrey/Desktop/kamilar.csv"
d1<- read.csv(d, header = TRUE, sep = ",", stringsAsFactors = FALSE)
head(d1)
```

```{r}
library(ggplot2)
g<-ggplot(data = d1, aes(x = Brain_Size_Species_Mean, y = MaxLongevity_m))
g<-g + geom_point()
g <- g + geom_smooth(method = "lm", formula = y ~ x)
g
```          
```{r}
d2<-na.omit(d1)
l<-(d2$MaxLongevity_m)
b<-(d2$Brain_Size_Species_Mean)
beta1 <- cor(l, b) * (sd(l)/sd(b))
beta1 
#this should be slope
```

```{r}
#i don't know if this is necessary
m<-lm(MaxLongevity_m ~ Brain_Size_Species_Mean, data = d1)
summary(m)

t <- coef(summary(m))
t <- data.frame(unlist(t))
colnames(t) <- c("MaxLongevity_m")
t
```
